spring.application.name=bank-recommendation-service
server.port=5432

# H2 Database configuration
spring.datasource.url=jdbc:h2:file:./transaction;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=postrage
spring.datasource.password=qwerty1234

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Logging configuration
logging.level.ru.example.bank=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

# Swagger
springfox.documentation.swagger-ui.enabled=true